import { RoomBooking, EventBooking, FoodBooking } from "./types";

// Dummy data for all bookings (will be filtered by component type)
export const bookingData: (RoomBooking & EventBooking & FoodBooking)[] = [
  {
    id: "B001",
    transactionNumber: "TRX-20250310-001",
    customerName: "John Doe",
    phoneNumber: "081234567890",
    roomType: "VVIP",
    console: "PlayStation 5",
    unitNumber: "Unit A",
    totalPerson: 4,
    date: "2025-03-10",
    time: "13:00 - 15:00",
    startTime: "13:00",
    endTime: "15:00",
    duration: "2 hours",
    status: "booking_success",
    amount: 150000,
    paymentMethod: "BCA Transfer",
    foodItems: ["Mineral Water", "Snack Combo", "Coffee"],
    foodTypes: ["Food", "Drink", "Food"],
    eventType: "Birthday Party",
    eventDescription: "Test event Desc",
    eventName: "John's 25th Birthday",
  },
  {
    id: "B002",
    transactionNumber: "TRX-20250310-002",
    customerName: "Jane Smith",
    phoneNumber: "081298765432",
    roomType: "VIP",
    console: "PlayStation 5",
    unitNumber: "Unit B",
    totalPerson: 2,
    date: "2025-03-10",
    time: "16:00 - 18:00",
    startTime: "16:00",
    endTime: "18:00",
    duration: "2 hours",
    status: "booking_ongoing",
    amount: 120000,
    paymentMethod: "QRIS",
    foodItems: ["Cola", "Popcorn"],
    foodTypes: ["Food", "Drink"],
    eventType: "Gathering",
    eventDescription: "Test event Desc",
    eventName: "Team Building",
  },
  {
    id: "B003",
    transactionNumber: "TRX-20250311-001",
    customerName: "Robert Johnson",
    phoneNumber: "081345678901",
    roomType: "Regular",
    console: "PlayStation 4",
    unitNumber: "Unit C",
    totalPerson: 3,
    date: "2025-03-11",
    time: "10:00 - 12:00",
    endTime: "12:00",
    startTime: "10:00",
    duration: "2 hours",
    status: "booking_finish",
    amount: 80000,
    paymentMethod: "Cash",
    foodItems: ["Tea", "Sandwich"],
    foodTypes: ["Food", "Drink"],
    eventType: "Tournament",
    eventDescription: "Test event Desc",
    eventName: "FIFA Championship",
  },
  {
    id: "B004",
    transactionNumber: "TRX-20250311-002",
    customerName: "Emily Davis",
    phoneNumber: "081456789012",
    roomType: "VVIP",
    console: "PlayStation 5",
    unitNumber: "Unit C",
    totalPerson: 5,
    date: "2025-03-11",
    time: "14:00 - 16:00",
    startTime: "14:00",
    endTime: "16:00",
    duration: "2 hours",
    status: "booking_canceled",
    amount: 150000,
    paymentMethod: "BRI Transfer",
    foodItems: ["Juice Pack", "Chips"],
    foodTypes: ["Food", "Drink"],
    eventType: "Corporate",
    eventDescription: "Test event Desc",
    eventName: "Product Launch",
  },
  {
    id: "B005",
    transactionNumber: "TRX-20250312-001",
    customerName: "Michael Wilson",
    phoneNumber: "081567890123",
    roomType: "VIP",
    console: "PlayStation 5",
    unitNumber: "Unit D",
    totalPerson: 3,
    date: "2025-03-12",
    time: "11:00 - 13:00",
    startTime: "11:00",
    endTime: "13:00",
    duration: "2 hours",
    status: "return",
    amount: 120000,
    paymentMethod: "Debit Card",
    foodItems: ["Energy Drink", "Burger"],
    foodTypes: ["Food", "Drink"],
    eventType: "Birthday Party",
    eventDescription: "Test event Desc",
    eventName: "Mike's Birthday",
  },
  {
    id: "B006",
    transactionNumber: "TRX-20250312-002",
    customerName: "Sarah Brown",
    phoneNumber: "081678901234",
    roomType: "Regular",
    console: "PlayStation 4",
    unitNumber: "Unit D",
    totalPerson: 2,
    date: "2025-03-12",
    time: "17:00 - 19:00",
    startTime: "17:00",
    endTime: "19:00",
    duration: "2 hours",
    status: "booking_reschedule",
    amount: 80000,
    paymentMethod: "QRIS",
    foodItems: ["Iced Tea", "Fries"],
    foodTypes: ["Food", "Drink"],
    eventType: "Casual",
    eventDescription: "Test event Desc",
    eventName: "Game Night",
  },
  {
    id: "B007",
    transactionNumber: "TRX-20250313-001",
    customerName: "David Miller",
    phoneNumber: "081789012345",
    roomType: "VVIP",
    console: "PlayStation 5",
    unitNumber: "Unit E",
    totalPerson: 4,
    date: "2025-03-13",
    time: "12:00 - 14:00",
    startTime: "12:00",
    endTime: "14:00",
    duration: "2 hours",
    status: "booking_success",
    amount: 150000,
    paymentMethod: "Credit Card",
    foodItems: ["Coffee", "Cake"],
    foodTypes: ["Food", "Drink"],
    eventType: "Corporate",
    eventDescription: "Test event Desc",
    eventName: "Team Meeting",
  },
  {
    id: "B008",
    transactionNumber: "TRX-20250313-002",
    customerName: "Lisa Taylor",
    phoneNumber: "081890123456",
    roomType: "Regular",
    console: "PlayStation 4",
    unitNumber: "Unit F",
    totalPerson: 2,
    date: "2025-03-13",
    time: "15:00 - 17:00",
    startTime: "15:00",
    endTime: "17:00",
    duration: "2 hours",
    status: "booking_ongoing",
    amount: 80000,
    paymentMethod: "QRIS",
    foodItems: ["Soda", "Pizza"],
    foodTypes: ["Food", "Drink"],
    eventType: "Tournament",
    eventDescription: "Test event Desc",
    eventName: "Racing Championship",
  },
];
